### ISSUE TITLE
Use Docker multi-stage builds

### ISSUE THREAD

**Issue by miwurster** [UST-MICO/mico#123]
Use a [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build) setup for our Docker images (`mico-admin` and `mico-core`). 

Examles:
* <https://github.com/OpenTOSCA/container/blob/master/Dockerfile>
* <https://github.com/OpenTOSCA/winery/blob/ustutt/Dockerfile>

**Comment by wagnerdk** [comment]
A multi-stage build for mico-core is located in the branch mico137-setup-script.
