### ISSUE TITLE
Create REST endpoint for service status

### ISSUE THREAD

**Issue by miwurster** [UST-MICO/mico#147]
As a user, I can retrieve basic information about a running MICO service by calling `GET /service/{shortName}/{version}/status` on `mico-core`. We must present every valuable information we can query thru the basic Kubernetes APIs, e.g., general service/pod health, running on which nodes, service/pod/node performance metrics, etc. Data is fetched on-demand.

**Comment by davidkopp** [comment]
I installed [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics) to the cluster. It provides some more metrics that could be useful for the service status endpoint. All the new metrics have the prefix `kube_`
