### ISSUE TITLE
Create view component to present service status

### ISSUE THREAD

**Issue by miwurster** [UST-MICO/mico#148]
As a user, I can inspect the status for a MICO service via `mico-admin`. Create a separate view component in `mico-admin` for that. Consult Team Monday how to integrate this component into the current state. 
Related to #146. Depends on #147, #392.

Figure 1 (does not have to look like this ;-)):
![image](https://user-images.githubusercontent.com/2610997/49794311-920aa580-fd37-11e8-9159-c053a22f7e47.png)

**Comment by gepperho** [comment]
blocked until #392 is done. Also related: #419
