### ISSUE TITLE
Cross-Origin Policy

### ISSUE THREAD

**Issue by gepperho** [UST-MICO/mico#174]
As a developer, I want a more specific cross-origin policy than *.

For simplicity * was set as cross-origin policy. This should be fixed.

**Comment by JanVetter** [comment]
@gepperho Add more context and information to the bug report, please.

**Comment by gepperho** [comment]
In REST/ServiceController.java is a class annotation (@CrossOrigin(origins = "*", maxAge = 3600)).

Due to this annotations, every origin is accepted. The default (without any annotation) was more restrictive, which led to an error in the UI. The UI was not allowed to to access the mico-core, since it came from the origin locahost:4200.

The policy should be as restrictive as possible, while still allowing requests from the UI (the local UI on 4200 as well as some hosted UI later).

**Comment by gepperho** [comment]
see #182 
similar problem with swagger endpoints (however, with the policy being to restrictive)
