### ISSUE TITLE
Apply version label to Kubernetes objects and check how labels can be applied to automatically created pods

### ISSUE THREAD

**Issue by wagnerdk** [UST-MICO/mico#253]
For solving issue #147 I need to retrieve information about services, pods, and deployments. To get the required information I need to know the format of the labels which are attached to the entities. Is the key always "app" and does the value contain a name and the version?

**Comment by JakobBenz** [comment]
We will use two labels:

- 'app' which will contain the short name of the (MICO) service, and
- 'versions' which will contain the version (string) of the (MICO) service.

Those labels will be applied to each (Kubernetes) Deployment and (Kubernetes) Service.

TODO:
- [ ] check how labels are/can automatically also (be) applied to (Kubernetes) Pods.
