### ISSUE TITLE
Store applications in database

### ISSUE THREAD

**Issue by miwurster** [UST-MICO/mico#27]
As a developer I want to store application definitions in a database.

Like #7

**Comment by JanVetter** [comment]
We might need to adapt the method `findByName`. Currently, it is not possible to implement the following:
```
Application storedApplication = serviceRepository.findByName("Application");
```

**Comment by JanVetter** [comment]
Added some **TODO**s to source code, see [`MicoCoreApplicationTests.java`](https://github.com/UST-MICO/mico/blob/feature/mico27-store-application/mico-core/src/test/java/io/github/ust/mico/core/MicoCoreApplicationTests.java).
