### ISSUE TITLE
Ignore id if set in post requests

### ISSUE THREAD

**Issue by buehlefs** [UST-MICO/mico#275]
- [x] This issue/feature is not reported yet
- [x] I built the project based on the latest master
- [x] I have checked the documentation to see if there is a procedure described for this case

---

## Expected behavior

POST for service or applications ignores the id in the json provided by a user even if it has a value.

## Actual behavior

The id is used to match the db node which leads to a variety of errors.

Examples:

Does not save an application if id is set even if the response is 201
Posting a new service can merge with an application with the same id in the db.

## How can the issue be reproduced?

Use the swagger ui to post a service or application and don't delete the id field from the json.

**Comment by miwurster** [comment]
Why not just setting the `id` property for POST controllers to `null`?
