### ISSUE TITLE
Initialize lists properly if Lombok @NoArgsConstructor is used

### ISSUE THREAD

**Issue by wagnerdk** [UST-MICO/mico#282]
We use multiple lists in our domain model. If one uses the builder provided by @Builder the lists are initialized with an empty list. If the Constructor provided by @NoArgsConstructor is used to construct the object, this initialization will not happen. This could result in a NPE. For more information read [Lombok Issue #1347
](https://github.com/rzwitserloot/lombok/issues/1347). The solution which seems to fix the issue is to provide a NoArgsConstructor which does the initialization. I think further investigation is necessary.

**Comment by JakobBenz** [comment]
No easy solution available after some research. However, the following possibilities exist:

1. (Manually) add a public no-args-constructor to each class in the domain model which contains at least one field that has a type, which needs to be initialized in case the builder is not used (e.g., some java.util.List implementation). Probably the quickest solution for now, but everytime a field is added to the class, the constructor needs to be checked, too (easily overlooked, modifiability). 

2. Just initialize the field directly when it's declared and add the `@Default` annotation for the builder. As a consequence, the `@Singular` annotation can't be used on such fields anymore (`@Default` and `@Singular` cannot be used together). Additionally, you're required to pass a `List` of items as a parameter when constructing instances of such domain model classes.

3. As a workaround for the missing `@Singular` annotation, we could write a helper class for each field that needs to be initialized, e.g., a `List`of `MicoServiceInterface`s. The helper class provides the functionality to construct, e.g., a `List`of `MicoServiceInterface`s in a builder like way.

**Comment by davidkopp** [comment]
Another option would be to don't use the Builder feature of Lombok at all.

To still use the builder pattern we could use the generation feature of the IDE (e.g. [Intellij Builder Generator](https://plugins.jetbrains.com/plugin/6585-builder-generator) to generate builder classes. I think it wouldn't lead to much more effort. The only problem I see, is that we would have no `@Singular` functionality anymore.

**Comment by JakobBenz** [comment]
Another other option is to not use the Builder pattern at all. Based on the experience of the last weeks I think we don't really need immutable objects.

The fluent API can also be achieved with Lombok's `@Accessor(fluent|chain = true)`annotation.

The only effort would be to update all implementations using domain model objects with a Lombok Builder.
