### ISSUE TITLE
Reevaluate association between MicoService and the MicoDeploymentInfos

### ISSUE THREAD

**Issue by davidkopp** [UST-MICO/mico#288]
Currently, MicoDeploymentInfos are stored as a list in MicoApplication per service (ID of service is used as key).
Problem: MicoService is used for the deployment and also includes the image name (redundant information).
MicoDeploymentInfo should be another edge between MicoApplication and MicoService in the Neo4j database.

![img_20190128_164238](https://user-images.githubusercontent.com/23580428/51847525-2945af80-231c-11e9-89bf-86e6248e406c.jpg)

- [x] Adjust domain model.
- [ ] Adjust also MicoKubernetesClient.
- [ ] Check every call to the Kubernetes API (ClusterAwareness) which retrieves resources based on names. Use label-based solution from now on.

**Comment by JakobBenz** [comment]
Deployment information actually is stored in a map in MicoApplication mapping from the (MICO) service id to the service deployment info. It seems that there is a problem with Neo4j and persisting maps (see also #287).

Possible solution: use `MicoServiceDeploymentInfo` as a `@RelationshipEntity` between `MicoApplication`and `MicoService`. That way, `MicoApplicationDeploymentInfo`becomes obsolete and can be removed.

**Comment by JakobBenz** [comment]
`MicoServiceDeploymentInfo` is now a `RelationshipEntity`and stored on the edge between `MicoApplication`and `MicoService`. `MicoServiceDependency`extends `MicoServiceDeploymentInfo`.

[MICO.pdf](https://github.com/UST-MICO/mico/files/2832510/MICO.pdf)

**Comment by JakobBenz** [comment]
Note that the inheritance between `MicoServiceDependency`and `MicoServiceDeploymentInformation` is not possible with Neo4j relationship entities. For now, I suggest to use the `MicoServiceDependency`class as it is, if we need the deployment information stuff also for `MicoServiceDependency`, we can still add it.
