### ISSUE TITLE
Fix GET publicIP

### ISSUE THREAD

**Issue by davidkopp** [UST-MICO/mico#336]
Request:
```
curl -X GET \
  http://localhost:8080/services/hello/v1.0.0/interfaces/hello-service/publicIP/ \
  -H 'Accept: application/hal+json' 
```

Response:
```
{
    "timestamp": "2019-01-30T15:51:19.774+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "No message available",
    "path": "/services/hello/v1.0.0/interfaces/hello-service/publicIP/"
}
```

Exception:
```
java.lang.NullPointerException: null
        at io.github.ust.mico.core.REST.ServiceInterfaceController.getInterfacePublicIpByName(ServiceInterfaceController.java:77) ~[classes!/:1.0-SNAPSHO
```

**Comment by JakobBenz** [comment]
Seems to be an issue related to the MICO Setup in Kubernetes (Swagger also not available).
Endpoint works just fine with a mocked list of public IPs.

**Comment by davidkopp** [comment]
@JakobBenz Sorry. I made some tests the last minutes, therefore `mico-core` was not available.
Not `mico-core` runs again.

**Comment by JakobBenz** [comment]
@davidkopp no problem.
I cannot reproduce the NPE, i get the following message:
`"Operation: [get]  for kind: [Service]  with name: [hello]  in namespace: [mico-workspace]  failed."`

**Comment by davidkopp** [comment]
Maybe.

While testing I indicated another problem regarding the creation of Kubernetes services:
`GET /services` returns all service object including the `serviceInterfaces`.
`GET /services/hello/v1.0.0` returns the service object including the `serviceInterface` but without the ports.
`GET /applications/hello/v1.0.0` returns the application with the including `services` but without the `serviceInterfaces`.

Especially the last problem leads to the creation of just a Kubernetes deployment but no Kubernetes service (because there is no `serviceInterface` included).

**Comment by JakobBenz** [comment]
I will check these endpoints as part of #340.

**Comment by JakobBenz** [comment]
It seems there is a problem with some Kubernetes Secret and the Fabric8io KubernetesClient.
