### ISSUE TITLE
Create endpoints to retrieve and update service deployment information

### ISSUE THREAD

**Issue by davidkopp** [UST-MICO/mico#346]
Create the following endpoints regarding service deployment information:

- [ ] `GET applications/{applicationShortName}/{applicationVersion}/services/{serviceShortName}` to get the `MicoServiceDeploymentInfoDTO`
- [ ] `PUT applications/{applicationShortName}/{applicationVersion}/services/{serviceShortName}` to update the deployment information of a `MicoService`. Request body is `MicoServiceDeploymentInfoDTO`.

The service version is not needed as a path variable since an application can only contain one version of a service.

See evaluation in #476 → [result](https://github.com/UST-MICO/mico/issues/476#issuecomment-467370359)

Depends on #288
Required for #313 
Required for #478

**Comment by miwurster** [comment]
Check if endpoints exist (and implement if they are missing).
