### ISSUE TITLE
Fix delete Service Endpoint

### ISSUE THREAD

**Issue by gepperho** [UST-MICO/mico#363]
## Expected behavior
When Delete services/{shortName}/{version} is called, the service should be deleted and never found again (if not used in an application/deployed).

## Actual behavior [in case of an issue]

Deleting services works sometimes. Most of the time a 200 OK message is returned and the service is **not** deleted.

## How can the issue be reproduced [in case of an issue]?

I was not able to reproduce this error yet. (Not deleting worked most of the time, deleting not)

**Comment by wagnerdk** [comment]
I could pinpoint the problem. The query which is used to delete the service only works if at least one interface with at least one port is associated with the service. I think I have to coordinate with @JakobBenz to improve it.
