### ISSUE TITLE
Fix Put Application/{shortName}/{version}

### ISSUE THREAD

**Issue by gepperho** [UST-MICO/mico#372]
## Expected behavior

The Endpoint should work analog to the PUT service endpoint.

## Actual behavior [in case of an issue]

When using mico-admin-ui, an 404 error is given. When using the exact same json string in the swagger ui, the endpoint works.

![image](https://user-images.githubusercontent.com/27412518/52224032-50195e00-28a7-11e9-8bc7-d22472788a45.png)

## How can the issue be reproduced [in case of an issue]?

On branch feature/mico-70-ui-to-edit-applications try to edit an application in the Application Data tab from the application-detail view.

**Comment by gepperho** [comment]
request with a tailing / also fail with a 404 error

**Comment by buehlefs** [comment]
url is wrong. use `/applications` with plural s!
