### ISSUE TITLE
Dockerize RealWorld frontend

### ISSUE THREAD

**Issue by miwurster** [UST-MICO/mico#384]
Choose a [frontend](https://github.com/gothinkster/realworld) technology, create Dockerfile and put everything to a separate GitHub repository (under UST-MICO).

**Comment by wagnerdk** [comment]
Created: [react-redux-realworld-example-app](https://github.com/UST-MICO/react-redux-realworld-example-app)
Added Docker multi-stage build here: [Dockerfile](https://github.com/UST-MICO/react-redux-realworld-example-app/commit/98561e4b766e8b9302548f1e3da0307e3d166b22)
