### ISSUE TITLE
Dockerize RealWorld backend

### ISSUE THREAD

**Issue by miwurster** [UST-MICO/mico#385]
Choose a [backend](https://github.com/gothinkster/realworld) technology, create Dockerfile and put everything to a separate GitHub repository (under UST-MICO).

**Comment by wagnerdk** [comment]
Created: [Realworld App in UST-MICO](https://github.com/UST-MICO/spring-boot-realworld-example-app)
Fixed docker build and created upstream [PR](https://github.com/gothinkster/spring-boot-realworld-example-app/pull/14)
