### ISSUE TITLE
Manage RealWorld application (undeploy old application)

### ISSUE THREAD

**Issue by miwurster** [UST-MICO/mico#391]
As a user, I can undeploy old application versions. See t4 in attached screenshot.

![1549634390226-123c2351-2234-4db4-af98-7ab2bdbec735](https://user-images.githubusercontent.com/2610997/52482812-8fe78a80-2bb2-11e9-94c1-1969ee15598e.jpg)

**Comment by JakobBenz** [comment]
Duplicate with #313.
