### ISSUE TITLE
REST endpoint to expose deployment information of deployed services

### ISSUE THREAD

**Issue by miwurster** [UST-MICO/mico#392]
As a user, I can use a REST endpoint to retrieve runtime information about deployed services:

- how many instances
- pod information (status, running on which node, restarts, age)
- Cpu/memory load on pods (or per service)
- cluster ip address information

See screenshot in #148 

Validate if #147 provides this information.

**Comment by davidkopp** [comment]
Extract the implementation of method `getStatusOfApplication` in `ApplicationController` into an own service class (package `service`). Reason: It's easier to reuse and test.
