### ISSUE TITLE
FIX POST Application

### ISSUE THREAD

**Issue by gepperho** [UST-MICO/mico#422]
## Expected behavior

When using the post application endpoint, all transferred data should be used (e.g. services).

## Actual behavior [in case of an issue]

The applications service list is ignored.

## How can the issue be reproduced [in case of an issue]?

Try the promote next version button in #421

**Comment by davidkopp** [comment]
@gepperho @miwurster @JakobBenz @spethso 

There are some open questions that have to be considered:

* What should happen, if a MicoService does not exist?
   * Create this MicoService?
      * No, because the application endpoint MUST NOT create, modify or delete MicoServices
   * Ignore it?
      * No, because that would lead to an inconsistent state of the application resource
   * Throw an error?
     * Yes, because a MicoService MUST exist before a MicoApplication is able to use it
HTTP Status code:  *422 Unprocessable Entity*
* What should happen, if a MicoService exists with the same `shortName` and `version` but different `gitCloneUrl`?
   * Update this MicoService?
      * No, because application endpoint MUST NOT create, modify or delete MicoServices
   * Ignore it?
      * No, because that would lead to an inconsistent state of the application resource
   * Throw an error?
     * Yes, because the MicoService MUST exist with the data that is expected by the client. Therefore it is required to check all data (not only `shortName` and `version`.
HTTP Status code:  *409 Conflict* / *422 Unprocessable Entity*

The POST application endpoint MUST only accept the request if one of the following two situations is fulfilled:
* List of `services` is empty
* List of `services` includes only valid MicoServices. Valid means, that for the given `shortName` and `version` a MicoService exists AND if more properties are given they MUST match the data stored in the database.

--- 

Until now I only mentioned the `services` property of a MicoApplication entity. The procedure should be the same for other sub resources like the `interfaces` property of a MicoService entity.

**Comment by miwurster** [comment]
+1 as described from @davidkopp.

**Comment by davidkopp** [comment]
The issue does not only apply to the POST application endpoint `createApplication`. The POST application endpoint `addServiceToApplication` and PUT application endpoint `updateApplication` have also to be fixed. I will do that all in one pull request #441.
