### ISSUE TITLE
Update developer documentation about integration tests

### ISSUE THREAD

**Issue by davidkopp** [UST-MICO/mico#430]
Update [documentation of `mico-core` integration tests](https://mico-dev.readthedocs.io/en/latest/mico-core/tests/integration-tests.html):

- [x] Use annotation `@Category(IntegrationTests.class)`
- [x] Special Dockerfiles -> Jenkins uses them to execute integration tests
- [x] Requirements (Kubernetes and DockerHub credentials)

**Comment by spethso** [comment]
See `/docs/mico-core/tests/integration-test.rst`
