### ISSUE TITLE
[UI] Add version selection when crawling GitHub repo

### ISSUE THREAD

**Issue by JanVetter** [UST-MICO/mico#462]
As a user, I want to have to possibility to select a specific version to crawl for a given GitHub repo.

As a developer, I want to make use of the provided API endpoint for getting the latests available versions of a provided GitHub repo.

Related issue: #314 .

You will get something like
```
[
  "2.0.2",
  "2.0.1",
  ...
  "1.6.11",
  "1.6.10"
]
```

**Comment by gepperho** [comment]
Workflow
1. 
take repository (link)
2.
choose:
- latest
- specific
