### ISSUE TITLE
Evaluate how to handle deployment information when creating and updating resources.

### ISSUE THREAD

**Issue by JakobBenz** [UST-MICO/mico#476]
@davidkopp @JanVetter 

Two scenarios:
1. Add existing `MicoService` to existing `MicoApplication`.
2. Create Kubernetes resources for `MicoService`.

In both cases, do we ...
- assume that the corresponding deployment information is already specified and available in the database and throw an exception if not, OR
- do we check whether the corresponding deployment information is already specified and available in the database and then use it if it's available and otherwise simply use the default deployment information.

**Comment by JanVetter** [comment]
Use default deployment information, if user did not specify anything else.

**Comment by JakobBenz** [comment]
I think that this is a check best done in the UI as some kind of validation when the user presses the "OK" / "Create" button to create an application and the "Add" button to add a service to an application, respectively.

We then can decide whether it should be mandatory or optional to specify some deployment information and show a corresponding hint or dialog.

**Comment by davidkopp** [comment]
We should definitely provide the possibility to add a new deployment information for a MicoService when a MicoService is added to a MicoApplication (method `addServiceToApplication`). Furthermore this MUST be the only possibility to provide a new deployment information.
However the deployment information (request body) can be omitted (is optional), so the backend use implicitly the default deployment information for this specific `MicoServiceDeploymentInfo`.
The endpoint for creating and updating a MicoApplication MUST NOT accept requests that includes service deployment information (`serviceDeploymentInfos`) → 422 Unprocessable Entity.

The UI SHOULD warn the user if no deployment information is provided but after a OK make the request (→ default information will be used).

There should be another endpoint to be able to update existing deployment information for a specific MicoService that is used by a specific MicoApplication.

@gepperho Is this ok for you?

**Comment by gepperho** [comment]
seems good. However, we might discuss the details in person.
