### ISSUE TITLE
Endpoint to retrieve deployment information

### ISSUE THREAD

**Issue by miwurster** [UST-MICO/mico#479]
As a user, I can use a REST endpoint to retrieve the deployment information of each service that is part of an application.

**Comment by gepperho** [comment]
Not only retrieving, but also PUTting them is necessary (please put, don't post)

**Comment by davidkopp** [comment]
> Not only retrieving, but also PUTting them is necessary (please put, don't post)

Endpoint for updating existing deployment information is covered by #346

**Comment by davidkopp** [comment]
Duplicated with #346

**Comment by JanVetter** [comment]
@davidkopp If this issue is a duplicate, why didn't you delete it? Is there a reason for this?

**Comment by davidkopp** [comment]
Yes this issue is a duplicate. It can be deleted.

**Comment by davidkopp** [comment]
Is already implemented by PR #503
