### ISSUE TITLE
Backend code quality

### ISSUE THREAD

**Issue by miwurster** [UST-MICO/mico#481]
The following will be fixed:

- [x] To instantiate the *GitHubCrawler* use dependency injection (`Autowired`) -> **newer use `new` in service code**
  hint: use `@Component` as a class annotation for the *GitHubCrawler*
  will be covered by #455

- [x] To get a `RestTemplate` use dependency injection (`Autowired`) -> no `RestTemplateBuilder` required
  will be covered by #455

- [x] Improve logging of errors in *GitHubCrawler*:
  * Don't use two error logs. Use e.g. `log.error(e.getMessage(), e)`
  * Don't log the same error twice in *GitHubCrawler* and in *ServiceController*
  will be covered by #532 . Got merged in #546

- [x] Don't use `@JsonIgnore` for the field `service` in *MicoServiceDependency*. Use `JsonManagedReference` and `JsonBackReference` instead
  hint: use `JsonManagedReference` in *MicoService* and `JsonBackReference` in *MicoServiceDependency*

**Comment by wagnerdk** [comment]
Are #491, #490 duplicates?

**Comment by davidkopp** [comment]
> Are #491 and #490 duplicates?
As discussed with Michael this issue #481 is used by Team Monday.
So Team Tuesday needs something similar. However we decided to create individual issues instead of a big issue working as a bucket for all refactorings. Is there an argument against this approach?
