### ISSUE TITLE
Fix DELETE applications/{shortName}

### ISSUE THREAD

**Issue by gepperho** [UST-MICO/mico#498]
# Expected behavior

When the endpoint is called all versions of the applications are deleted, if not even a single version is deployed.

## Actual behavior [in case of an issue]

ALL applications are deleted. Further the deployment check seems not to work.

## How can the issue be reproduced [in case of an issue]?

via ui on `feature/mico-ui-maintenance`

**Comment by wagnerdk** [comment]
It seems that the [check](https://github.com/UST-MICO/mico/blob/391b8c5624874b6bc3fdbdff25f4da7c708a1f8a/mico-core/src/main/java/io/github/ust/mico/core/web/ApplicationController.java#L204) is implemented correctly. We should coordinate with @davidkopp  who implemented the method "isApplicationDeployed".

**Comment by gepperho** [comment]
might be, however deleting all applications (also those with a different shortName) is wrong and needs to be fixed.

**Comment by davidkopp** [comment]
I'm already working on a fix for the method `isApplicationDeployed` in #438.

**Comment by wagnerdk** [comment]
You are right. All Applications are deleted. I can fix this, but what should happen to services which are associated with an application? I think if we delete an application it is not necessary to delete all associated services right?

**Comment by davidkopp** [comment]
The association between a MicoApplication and a MicoService is a MicoServiceDeploymentInfo. If a MicoApplication is deleted, all deployment infos should be also deleted. The MicoServices should stay as they are.

**Comment by JakobBenz** [comment]
Exactly, if a node is deleted, all its relationships (edges) are deleted, too.
