### ISSUE TITLE
GET endpoints for application(s) should return new DTO with applications and all their services

### ISSUE THREAD

**Issue by JakobBenz** [UST-MICO/mico#504]
The development of the frontend would be facilitated by having the endpoints
 - `GET /applications`,
 - `GET /applications/{shortName}`, and
 - `GET /applications/{shortName}/{version}`
return a DTO which contains the applications and all services included in the application.

**Comment by JakobBenz** [comment]
@davidkopp What do you think?

**Comment by davidkopp** [comment]
Like discussed via Skype:
* Create a new DTO with the applications and their services
* Discuss with Heiko if there are more information useful like whether the application is deployed or not
* Create a new DTO for MicoApplication that does not include the `serviceDeploymentInfos` → will be used for create and update of a MicoApplication
