### ISSUE TITLE
Update all update endpoints (`PUT`) to return `204 No Content` without a response body.

### ISSUE THREAD

**Issue by JakobBenz** [UST-MICO/mico#507]
All `PUT`endpoints should consistently return `204 No Content` with an empty response body. See [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.6) for further details.

**Comment by JakobBenz** [comment]
@gepperho is that alright from a frontend developer point of view?

**Comment by buehlefs** [comment]
The RFC allows `200 OK` with content and that would allow the backend to send the updated data back. This allows the frontend to not immediately request the updated resource with a get.
And as there could be additional changes (in for example the service list of an application) getting the current state without another roundtrip (or worse the frontend guessing how the backend performs the changes) is more valuable then a cleaner PUT endpoint.

**Comment by davidkopp** [comment]
Like Fabian suggested to always use `200 OK` with content is ok for me. We just have to be consistent.
It makes sense to always response with the full object, because we have some resources that include embedded information that are not part of the request.

**Comment by JakobBenz** [comment]
Works for me, too. As all `PUT`endpoints currently return the respective updated resource, this issue can be closed.

See also #512.
