### ISSUE TITLE
Is min and max version in MicoServiceDependency required?

### ISSUE THREAD

**Issue by davidkopp** [UST-MICO/mico#513]
The properties `minVersion` and `maxVersion` in *MicoServiceDependency* are marked as required. However if they are set by the UI, they are ignored.

**Comment by gepperho** [comment]
In the UI, we pick a specific version of a service. Hence, we are setting min and max to the same value. Considering the workflow shown in #390 a specific version seems to be sufficient. 

Therefore, I see two possible ways to go:
- set min and max value to the same (by the ui given) version (preferred)
- change to one version field

**Comment by davidkopp** [comment]
Nevertheless we have to use the incoming version in the backend, that is currently not the case.

**Comment by davidkopp** [comment]
@gepperho PR #512 will remove the properties `minVersion` and `maxVersion`. The new DTO called `MicoServiceDependencyRequestDTO` will only include two properties:
* `shortName`
*  `version`

That is enough to add an existing service as a dependency. The affected endpoint is `POST /services/{shortName}/{version}/dependees createNewDependee`.
