### ISSUE TITLE
Check if all used Swagger extension properties are handled correctly in the UI

### ISSUE THREAD

**Issue by davidkopp** [UST-MICO/mico#533]
PR #455 introduced some new extension properties. 
Please check if they are useful for the UI. If yes, ensure they are handled correctly in the UI. If not, please inform me (@davidkopp).

Here is a summary of all currently used properties:
* `title`
* `x-order`
* `description`
* `minLength`
* `maxLength`
* `pattern`
* `default`
* `readOnly` (used currently only for `dependencies` in *MicoService* and `deploymentStatus` in *MicoApplicationDTO*)
* `minimum` (used currently only for `replicas` and `minReadySecondsBeforeMarkedAvailable` in *MicoServiceDeploymentInfo* and for `port` and `targetPort` in *MicoServicePort*)
* `maximum` (used currently only for `port` and `targetPort` in *MicoServicePort*)
* `minItems` (used currently only for `ports` in *MicoServiceInterface*)

**Comment by gepperho** [comment]
readOnly is not used, since those attributes are already filtered

**Comment by gepperho** [comment]
DataView:
 - [ ]`title`
 - [ ]`x-order`
 - [ ]`description`
 - [ ]`minLength`
 - [ ]`maxLength`
 - [ ]`pattern`
 - [ ]`default`
 - [ ]`readOnly` (used currently only for `dependencies` in *MicoService - [ ]and `deploymentStatus` in *MicoApplicationDTO*)
 - [ ]`minimum` (used currently only for `replicas` and `minReadySecondsBeforeMarkedAvailable` in *MicoServiceDeploymentInfo - [ ]and for `port` and `targetPort` in *MicoServicePort*)
 - [ ]`maximum` (used currently only for `port` and `targetPort` in *MicoServicePort*)
 - [ ]`minItems` (used currently only for `ports` in *MicoServiceInterface*)

**Comment by gepperho** [comment]
Forms:
 - [x] `title`
 - [x] `x-order`
 - [ ] `description`
 - [ ] `minLength`
 - [ ] `maxLength`
 - [ ] `pattern`
 - [ ] `default`
 - [ ] `readOnly` (used currently only for `dependencies` in *MicoService - [ ]and `deploymentStatus` in *MicoApplicationDTO*)
 - [ ] `minimum` (used currently only for `replicas` and `minReadySecondsBeforeMarkedAvailable` in *MicoServiceDeploymentInfo* and for `port` and `targetPort` in *MicoServicePort*)
 - [ ] `maximum` (used currently only for `port` and `targetPort` in *MicoServicePort*)
 - [ ] `minItems` (used currently only for `ports` in *MicoServiceInterface*)
