### ISSUE TITLE
Information for extended scenario service deployment

### ISSUE THREAD

**Issue by spethso** [UST-MICO/mico#555]
As a frontend developer, I want to know, which information, e.g. environment variables or interface definitions, deployment information, are needed to deploy the extended scenario services. 

Document it in the developer documentation.

**Comment by miwurster** [comment]
@wagnerdk as you created the Docker images, can you help here what values the environment variables need to have?

**Comment by wagnerdk** [comment]
The information about the environment variable is [here](https://github.com/UST-MICO/react-redux-realworld-example-app#docker-build).

**Comment by miwurster** [comment]
Please specify here in this issue the exact variable name and value to use (based on an example). This would really help others to quickly grasp the necessary information.

**Comment by wagnerdk** [comment]
Only one variable is necessary. This is:`BACKEND_REST_API`. To test only the front end it is possible to use
`conduit.productionready.io/api` as a value (The ` http://` is added by the nginx.conf, comparable to the nginx.conf used in our own front end). This uses the API which is provided by the authors of the real world example. To connect the front end with the backend the environment variable has to be set to the address of the back end. I don't know exactly how this is handled in our kubernetes client. Maybe @davidkopp or @JakobBenz could help here. The front end is than exposed at the container port 80.

The [back end](https://github.com/UST-MICO/spring-boot-realworld-example-app) does not need environment variables. It exposes its API at the container port 8080.

**Comment by davidkopp** [comment]
It is required to set the environment variable as part of the service deployment information. The UI has already implemented this.

The specific API of `mico-core` is `PUT /applications/{shortName}/{version}/deploymentInformation/{serviceShortName}` e.g. with the body
```
{
    "environmentVariables": [
        {
            "name": "BACKEND_REST_API",
            "value": "conduit.productionready.io/api"
        }
    ]
}
```

**Comment by davidkopp** [comment]
We improved the workflow to setup connections between MICO services (e.g. between a frontend and a backend) with the PR #595.

A user has to provide 3 information to connect the frontend with a backend:
* the name of the environment variable used by the frontend (e.g. `BACKEND_REST_API`)
* the short name of the MICO service to connect with (e.g. `spring-boot-realworld-example-app`)
* the name of the MICO service interface to connect with (e.g. `rest`)

These information are part of the service deployment information.
Example request:
```
curl -X PUT \
  'http://{{host}}/applications/{{shortName}}/{{version}}/deploymentInformation/{{serviceShortName-frontend}}' \
  -d '{
    "replicas": 1,
    "labels": [
        {
            "key": "component",
            "value": "frontend"
        }
    ],
    "environmentVariables": [],
    "interfaceConnections": [
        {
            "environmentVariableName": "BACKEND_REST_API",
            "micoServiceShortName": "spring-boot-realworld-example-app",
            "micoServiceInterfaceName": "rest"
        }
    ],
    "imagePullPolicy": "IfNotPresent"
}'
```

**Comment by davidkopp** [comment]
Is documented in the user documentation as part of the tutorials:
https://mico-docs.readthedocs.io/en/latest/tutorials/04-manage-an-application.html#editing-deployment-information-of-services
