### ISSUE TITLE
[UI] Show kube config in UI

### ISSUE THREAD

**Issue by spethso** [UST-MICO/mico#557]
As a user, I want to view the kube config yaml in the UI.
See #99.

**Comment by gepperho** [comment]
Please elaborate:
Shall we 
- present the content from the yaml file like we present the data from other endpoints 
- or show the plain yaml file
in the ui?
Further, is some kind of download button for the yaml file required?

**Comment by davidkopp** [comment]
@Jojo134

**Comment by gepperho** [comment]
implemented in `feature/yaml_dto`
