### ISSUE TITLE
Restructure domain model representation of service deployment information.

### ISSUE THREAD

**Issue by JakobBenz** [UST-MICO/mico#562]
Currently, a `MicoServiceDeploymentInfo` (domain) object is represented as a `Relationship` in the database.

Since Neo4j does not allow composite types such as lists and maps as properties on relationships, and we need, to store environment variables and labels as part of the deployment information of a `MicoService`, `MicoServiceDeploymentInformation` needs to be stored as a `Node` in the database. 

The new graph schema will look like this:
![sdi-1](https://user-images.githubusercontent.com/10036684/54312221-a3817900-45d6-11e9-8efb-8d7239038104.png)

Considering `MicoService`s that depend on other `MicoService`s it is possible for a `MicoApplication` to specify deployment information also for the dependencies of the included `MicoService`s (see below for an example scenario).

![sdi-2](https://user-images.githubusercontent.com/10036684/54312227-a7150000-45d6-11e9-84c0-55061668c7c1.png)

The complete graph schema (including properties of `MicoServiceDeploymentInfo`) will look something like this:

![sdi-3](https://user-images.githubusercontent.com/10036684/54312966-8188f600-45d8-11e9-92f2-7ea498098389.png)

Fixes #556.

**Comment by buehlefs** [comment]
I would suggest decoupling the includes service edges completely from the deployment information to allow the application to specify deployment information also for the dependencies of included services. This  would need further work later down the line but there would be no extra work compared to this proposal if we don't support deployment information for service dependencies right now.

The graph would the look something like this:
(:application)-[:includes]->(:service)
(:application)-[:provides]->(:deployment_info)-[:for]->(:service)

**Comment by JakobBenz** [comment]
@buehlefs I actually had it that way in a previous draft version of the new schema but removed the edge between `MicoApplication` and `MicoService` again since I didn't see any benefit from it. Considering deployment information for service dependencies, this decoupling makes sense. For the updated graph schema see above.
