### ISSUE TITLE
Fix display of error messages in service status

### ISSUE THREAD

**Issue by davidkopp** [UST-MICO/mico#576]
If there are error messages in the status of a MicoService, they should be displayed. However the message is "No properties defined.":
![image](https://user-images.githubusercontent.com/7796322/54476801-add38b00-4801-11e9-83af-8733b6010c03.png)

The response of the request to the `/status` endpoint was:
```
{
    "requestedReplicas": 0,
    "availableReplicas": 0,
    "interfacesInformation": [],
    "applicationsUsingThisService": [],
    "podsInformation": [],
    "nodeMetrics": [],
    "errorMessages": [
        "No deployment of react-redux-realworld-example-app v1.0.0 is available."
    ]
}
```

**Comment by gepperho** [comment]
The API should offer the errorMessages as list of objects. Then the UI will handle it correct.
