### ISSUE TITLE
Fix update service deployment information removes relation to service node

### ISSUE THREAD

**Issue by davidkopp** [UST-MICO/mico#667]
After an update of a service deployment information the relation to the service is removed.

Edge `FOR` between the service (green node) and the service deployment information (brown node) is missing after an update:
![image](https://user-images.githubusercontent.com/7796322/55018745-c7d84f00-4ff3-11e9-839c-4c8cd2037ffe.png)

**Comment by davidkopp** [comment]
Error was introduced through [commit 91623aa6735fb3856fe13750084efa388563a5e7](https://github.com/UST-MICO/mico/commit/91623aa6735fb3856fe13750084efa388563a5e7#diff-30df7d4d947cad74f3bdfb7bbb880ac8)

**Comment by Pascal157600** [comment]
Yeah, it is not really a nice solution, but if it works, it is of course okay for me.
If the depth parameter works as intended, could this also solve this problem? If we define a save of the deployment info with depth 0, only the deployment info should be updated and the edges should all stay the same, right?

**Comment by davidkopp** [comment]
No, unfortunately a depth of 0 is not possible here. We need a depth of 1 to be able to update the nested Labels, Environment Variables and Interface Connections. However a depth of 1 will delete the edge to the service.
There are several ways to fix this, but I prefer the simple way of just using the DTO and apply the values directly on the entity loaded from the database.
