### ISSUE TITLE
Backend component to crawl Docker Hub

### ISSUE THREAD

**Issue by miwurster** [UST-MICO/mico#67]
As a developer, I provide a reusable service to crawl information from Docker Hub in order to extract service attributes automatically.

Docker Image = service name
Docker Tags = versions

Try to avoid APIs where authentication is required. Maybe check if there are so-called on-time access tokens (request one-time access token then issue actual request).

**Comment by JanVetter** [comment]
https://registry-1.docker.io/v2/

**Comment by JanVetter** [comment]
Auth required

**Comment by JanVetter** [comment]
Helpful information: https://www.baeldung.com/docker-java-api

**Comment by JanVetter** [comment]
It seems, that we always need to provide login credentials: https://github.com/docker/hub-feedback/issues/1103.
**TODO:** We need to check if we can get a one-time token to pull information of images.

**Comment by JanVetter** [comment]
Use this as sample repo for testing purposes: https://hub.docker.com/r/library/nginx/
