### ISSUE TITLE
Support custom cloud event headers

### ISSUE THREAD

**Issue by buehlefs** [UST-MICO/mico#730]
As a user i want to have out of the box support for the custom cloud event header fields specified by <https://mico-docs.readthedocs.io/en/latest/messaging/cloudevents.html>. The kafka to faas connector should be able to understand and use the header fields where generic handling is possible.

Add test cases for each custom field

Header fields that need special handling in our kafka-faas connector ([X] = implemented) :
- [x] route
- [x] routingslip #728
- [x] filteroutbeforetopic 
- [x] expirydate
- [x] dataref ?

**Comment by wagnerdk** [comment]
https://github.com/UST-MICO/kafka-faas-connector/commit/717868f4496122b17a99f570021c5cd81b2d163e
And support for unknown extensions:
https://github.com/UST-MICO/kafka-faas-connector/commit/33656b183481b1d927f50e49dc96685b87737d4a

**Comment by buehlefs** [comment]
The component needs to react to certain header fields like `filteroutbeforetopic`, `expirydate` and some others. The recent changes still ignore these fields (but at least preserve them if present...)

**Comment by buehlefs** [comment]
I will update this comment as i implement the header fields.

- [ ] Expiry date (current: message gets dropped)
- [ ] Route history

**Comment by wagnerdk** [comment]
I will update this comment as i implement the header field.

- [ ] filteroutbeforetopic

I think the dataref field should not be implemented by us because we can not know how a user wants to store its data for the claim check pattern. This should be implemented by a user-defined faas function.

**Comment by buehlefs** [comment]
We should close this issue after `createdfrom` is implemented and create extra issues like #739 for missing headers like `iserrormessage`.
