### ISSUE TITLE
Update error report message in doc and implementation

### ISSUE THREAD

**Issue by wagnerdk** [UST-MICO/mico#737]
Update the doc and the implementation of the error report message to include the original message as the "data" item and the error report fields as a header of the cloudevent envelope.

**Comment by buehlefs** [comment]
[Documentation is done.](https://mico-docs.readthedocs.io/en/latest/messaging/cloudevents.html)

new attributes:

- iserrormessage
- errormessage
- errortrace

Implementation will be covered by #739
