### ISSUE TITLE
Multiple instance deployment

### ISSUE THREAD

**Issue by wagnerdk** [UST-MICO/mico#743]
As a user, I want that I can deploy multiple instances of the same MICO service in two different applications with MICO such that the deployed services can have completely independent configurations.

See: #729

**Comment by davidkopp** [comment]
New property in *MicoApplication*:
```
private List<KafkaFaasConnectorDeploymentInfo> = new ArrayList<>();
```

New endpoints:
- `ApplicationResource`:
   - `addKafkaFaasConnectorToApplication`
   - `deleteKafkaFaasConnectorToApplication`
   - `getKafkaFaasConnectorDeploymentInformation`
   - `updateKafkaFaasConnectorDeploymentInformation`
- `KafkaFaasConnectorDeploymentInfo`:
   - `getKafkaFaasConnector`
   - `updateKafkaFaasConnector`
   - `promoteKafkaFaasConnector`
   - `deleteKafkaFaasConnector`

Change implementation of endpoints:
- `getApplicationDeploymentStatus`
- `getStatusOfApplication`

Notes:
- `KafkaFaasConnectorDeploymentInfo` should be addressed either by an `instanceId` per application or with a global unique ID. `instanceId` is unique per KafaFaasConnector within an application regardless of its version.
- 
- If we need an edge between the `MicoApplication` node and the KafkaFaasConnector node don't call `INCLUDES`.
