### ISSUE TITLE
Evaluate Istio vs. Envoy vs. xxx

### ISSUE THREAD

**Issue by miwurster** [UST-MICO/mico#75]
As a user, additional features to my MICO services are added automatically during deployment, e.g., telemetry collection (performance, monitoring), log collection.

Istio is a service mesh for Kubernetes and already provides a variety of features, such as Traffic Management and Telemetry. However, Istio employs the Envoy proxy in their sidecar concept in order to inject the features to the deployed services. We should evaluate if it makes sense to re-use the full-blown Istio eco-system for MICO (overhead, ease of use, how integrated in MICO etc.). It is probably enough to only use Envoy without the rest of Istio.

Outcome: ADR discussing the options

**Comment by davidkopp** [comment]
ADR finished: [Istio vs. Envoy](https://mico-docs.readthedocs.io/en/latest/adr/0017-istio-vs-envoy.html)
