### ISSUE TITLE
Fix msg_validator (M2)

### ISSUE THREAD

**Issue by davidkopp** [UST-MICO/mico#752]
Fix [msg-validator](https://github.com/UST-MICO/msg-validator):
- [x] Add Dockerfile
- [x] Remove CloudEvent implementation (pass message as is)
- [x] Adjust environment variables (see #748)

**Comment by wagnerdk** [comment]
Fixed with:
 - [Missing Dockerfile](https://github.com/UST-MICO/msg-validator/commit/6ceb1b4ffcceeb99cf1fcc2349917bd87e396163)
- [Remove CloudEvent implementation](https://github.com/UST-MICO/msg-validator/commit/e25b9f378071b89f03168f368f79e8f4bfa7e5e1)
