### ISSUE TITLE
Setup Jenkins to automatically deploy mico-core

### ISSUE THREAD

**Issue by davidkopp** [UST-MICO/mico#763]
See [Jenkins Setup](https://mico-docs.readthedocs.io/en/latest/setup/cicd.html#jenkins-setup) for more information

**Comment by wagnerdk** [comment]
Can we close this issue?

**Comment by davidkopp** [comment]
Jenkins works again. Updated [documentation](https://mico-docs.readthedocs.io/en/latest/setup/cicd.html).
